FROM amazonlinux:with-sources
MAINTAINER Marc Rosenthal <marc@affordabletours.com>

RUN yum update -y
# add nodejs repo
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN yum -y install nodejs

# update npm to latest version
RUN npm install -g npm

# install serverless framework
RUN npm install -g serverless@1.38.0
